// Copyright (c) 2026 Abdurrahman Konuk (professionally known as Ufuk Deniz Konuk)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// Built-in beam / frame library: buildings, bridges, industrial, towers, machines, vehicles,
// aerospace structures and models built around end releases (hinges / pins), as ready-to-solve
// models (geometry, catalogue sections, materials, supports, nodal and distributed loads, self
// weight, end releases).
//
// The files under assets/objects/beam/beam3D/ are generated by anaf_beam_library_tool (tools/) and
// must never be edited by hand; the test suite checks that they match the generator. Every model is
// written twice: <id>.msh (the model) and <id>_solved.msh (the same model with its results), both
// importable. Models use catalogue sections only, so loading one adds no user section.

#include <beam/beamProperties/meshData.hpp>
#include <beam/beamSection/beamSection.hpp>
#include <material/properties.hpp>

#include <expected>
#include <filesystem>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace FEM::BEAM::LIBRARY {

  // Relative to the assets folder (anaf::DIRECTORY::findAssetPath).
  inline constexpr std::string_view kLibrarySubdir = "objects/beam/beam3D";
  inline constexpr std::string_view kIndexFile = "index.json";

  struct Entry {
    std::string id;          // file name without ".msh": [a-z0-9_]+
    std::string name;        // shown in the GUI
    std::string category;    // Building, Bridge, Industrial, Energy & Tower, Machine & Vehicle, Aerospace, Hinges & Pins, Large Structures
    std::string description; // geometry, supports, loads, sections, material
  };

  struct LibraryBeam {
    Entry entry;
    MeshData mesh; // indices into the material and section lists given to buildLibrary()
  };

  // Every built-in model, in index order. materials / sections: the built-in lists
  // (assets/bridge/materialProperties.json, sectionCatalog.json). Throws std::runtime_error when
  // a name a model uses is not in them.
  std::vector<LibraryBeam> buildLibrary(std::span<const anaf::MATERIAL::Material> materials,
                                        std::span<const BeamSection> sections);

  // Writes <id>.msh, <id>_solved.msh (MSH 4.1 ASCII) and index.json into dir; returns the entries.
  std::expected<std::vector<Entry>, std::string> writeLibrary(const std::filesystem::path& dir,
                                                              std::span<const anaf::MATERIAL::Material> materials,
                                                              std::span<const BeamSection> sections);

  // index.json text (stable formatting, so the committed file can be compared).
  std::string indexJson(std::span<const Entry> entries);

  // Reads and checks index.json of a library folder.
  std::expected<std::vector<Entry>, std::string> loadIndex(const std::filesystem::path& indexFile);

  inline std::filesystem::path modelFile(const std::filesystem::path& libraryDir, const Entry& entry) {
    return libraryDir / (entry.id + ".msh");
  }
  inline std::filesystem::path solvedFile(const std::filesystem::path& libraryDir, const Entry& entry) {
    return libraryDir / (entry.id + "_solved.msh");
  }

} // namespace FEM::BEAM::LIBRARY end
